In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [3]:
print(x)

[['Japan' 33.0 60000.0]
 ['Indonesia' 55.0 40000.0]
 ['Vietnam' 70.0 55000.0]
 ['Indonesia' 45.0 65000.0]
 ['Japan' 78.0 nan]
 ['Vietnam' 76.0 40000.0]
 ['Indonesia' nan 66000.0]]


In [4]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No']


In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,1:3])
x[:, 1:3] =imputer.transform(x[:,1:3])

In [6]:
print(x)

[['Japan' 33.0 60000.0]
 ['Indonesia' 55.0 40000.0]
 ['Vietnam' 70.0 55000.0]
 ['Indonesia' 45.0 65000.0]
 ['Japan' 78.0 54333.333333333336]
 ['Vietnam' 76.0 40000.0]
 ['Indonesia' 59.5 66000.0]]


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [8]:
print(x)

[[0.0 1.0 0.0 33.0 60000.0]
 [1.0 0.0 0.0 55.0 40000.0]
 [0.0 0.0 1.0 70.0 55000.0]
 [1.0 0.0 0.0 45.0 65000.0]
 [0.0 1.0 0.0 78.0 54333.333333333336]
 [0.0 0.0 1.0 76.0 40000.0]
 [1.0 0.0 0.0 59.5 66000.0]]


In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
print(y)

[0 1 0 0 1 1 0]


In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=1)

In [12]:
print(x_train)

[[1.0 0.0 0.0 55.0 40000.0]
 [0.0 1.0 0.0 33.0 60000.0]
 [0.0 1.0 0.0 78.0 54333.333333333336]
 [1.0 0.0 0.0 45.0 65000.0]
 [0.0 0.0 1.0 76.0 40000.0]]


In [13]:
print(x_test)

[[1.0 0.0 0.0 59.5 66000.0]
 [0.0 0.0 1.0 70.0 55000.0]]


In [14]:
print(y_train)

[1 0 1 0 1]


In [15]:
print(y_test)

[0 0]


In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,3:] = sc.fit_transform(x_train[:,3:])
x_test[:,3:] = sc.transform(x_test[:,3:])

In [17]:
print(x_train)

[[1.0 0.0 0.0 -0.13741458973797505 -1.1565759035418088]
 [0.0 1.0 0.0 -1.3970483290027471 0.7927093271466322]
 [0.0 1.0 0.0 1.1794752285842867 0.24041184511824085]
 [1.0 0.0 0.0 -0.7099753803128714 1.2800306348187425]
 [0.0 0.0 1.0 1.0649630704693074 -1.1565759035418088]]


In [18]:
print(x_test)

[[1.0 0.0 0.0 0.12023776602072832 1.3774948963531646]
 [0.0 0.0 1.0 0.7214265961243695 0.305388019474522]]
